#!/usr/bin/env bash

# constants
readonly PROGNAME="$(basename "$0")"
readonly PROGDIR="${HOME}/Projects/dotfiles"
#readonly VERSION=$(cat "$PROGDIR/VERSION.md")
readonly TODAY=$(date +"%m-%d-%y") readonly ARGS="$@"

. ./bash/.functions
. ./bash/.symlink_functions

install_software() {
  install_homebrew
  install_brews
  install_npm
  install_xcode

  [[ $? ]] \
  && _print_success "Software installs complete"
}

install_homebrew() {
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew doctor
  [[ $? ]] \
  && _print_success "Installed Homebrew"
}

install_brews() {
  brew bundle
  [[ $? ]] \
  && _print_success "Installed Homebrew apps"
}

install_npm() {
  curl https://www.npmjs.org/install.sh | sh
  [[ $? ]] \
  && _print_success "Installed npm"
}

install_xcode() {
  xcode-select --install
  [[ $? ]] \
  && _print_success "Installed xcode-select"
}

update_vim_plugins() {
  vim +PluginInstall +PluginUpdate +qall
  [[ $? ]] \
  && _print_success "Updated Vim bundles"
}

main() {
  _is_empty "$PROGDIR" \
  && error_out

  source_bash

  cmdline "$ARGS"

  echo "Install everything, or skip to dotfiles?"
  select yn in "Everything" "Skip"; do
    case $yn in
    Everything ) install_software; break;;
    Skip ) break;;
    esac
  done

  _require_prog git "Git is required to use $PROGNAME" http://git-scm.com

  link_vim_files
  link_bash_files
  link_git_files
  link_tmux_files

  #setup_global_gitconfig

  update_vim_plugins

  _print_success "All done!"
}

main
