source ~/.bash_files/paths.bash

source ~/.bash_files/aliases.bash
source ~/.bash_files/colors.bash
source ~/.bash_files/git_functions.bash
source ~/.bash_files/git-completion.bash

PS1='
[\W] \[$(branch_color)\]$(parse_git_branch)\[${c_sgr0}\] → '
