# for file in ~/.bash*; do source $file; done
# for file in ~/.{path,bash_prompt,exports,aliases,functions,extra}; do
# for file in ~/bash; do
# 	[ -r "$file" ] && [ -f "$file" ] && source "$file"
# done

source ~/.bash/.aliases
source ~/.bash/.colors
source ~/.bash/.fzf
source ~/.bash/.git_completion
source ~/.bash/.paths
source ~/.bash/.prompt

if [ -f ~/.bash_profile.local ]; then
  source ~/.bash_profile.local
fi
