source ~/.bash/aliases.bash
source ~/.bash/colors.bash
source ~/.bash/git-functions.bash
source ~/.bash/git-completion.bash
source ~/.bash/fzf.bash
source ~/.bash/paths.bash

if [ -f ~/.bash_profile.local.bash ]; then
  source ~/.bash_profile.local.bash
fi

# Prompt
PS1='\[\e[34m\][\w] \[$(branch_color)\]$(parse_git_branch)\[${c_sgr0}\]\n→ '
