" Main .vimrc
" ---------------------------------

" Vundle
set nocompatible
filetype off
silent! set rtp+=~/.vim/bundle/Vundle.vim
silent! call vundle#begin()
source ${HOME}/.vim/settings/bundles.vim
call vundle#end()

" Settings
source ${HOME}/.vim/settings/mappings.vim

filetype plugin indent on

" These need to be moved... they dont belong here.
let vimDir = '$HOME/.vim'
let &runtimepath.=','.vimDir
let g:test#javascript#mocha#file_pattern = '.*\.tests\.js'
let test#javascript#mocha#executable = 'npm test'

au FileType * IndentGuidesEnable
